name: 'Hekto Deployer'
description: 'Deploy to Hekto'
inputs:
  token:
    description: 'token'
    required: true
  source:
    description: 'source'
    required: false
    default: './'
  url:
    description: 'url'
    reqired: false
    default: 'https://hekto.app'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.source }}
    - ${{ inputs.url }}
